version: '3.8'

services:

#backend
backened_service:
  build: ./backend
  container_name: my-app-backend
  restart: always
  enviroment: 
    - PORT=5050
  networks:
    - app-network

#frontend
frontend_service:
  build: ./frontend
  container_name: my-app-frontend
  restart: always
  ports :
    - "3000:80" 
  depends_on:
    -backened_service
  networks:
    - app-network

networks:
  app-network:
    driver: bridge        
